project_id = "dnodqhwwzdqfqlndwhsf"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.alert-postgres-error]
    verify_jwt = false
  [functions.chat-assist]
    verify_jwt = false
