// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my TrendFlux profile",
  description: "Return the signed-in TrendFlux user's profile row (name, email, phone, role).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("user_id, email, full_name, phone, created_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}, null, 2) }],
      structuredContent: { profile: data ?? null }
    };
  }
});

// src/lib/mcp/tools/list-my-enrollments.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_enrollments_default = defineTool2({
  name: "list_my_enrollments",
  title: "List my course enrollments",
  description: "List the signed-in user's TrendFlux Academy module enrollments with status and timestamps.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("module_enrollments").select("id, status, created_at, updated_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        { type: "text", text: JSON.stringify(data ?? [], null, 2) }
      ],
      structuredContent: { enrollments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-strategy-bookings.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var isoDate = z.string().describe("ISO 8601 date or datetime, e.g. 2026-07-01 or 2026-07-01T00:00:00Z").refine((s) => !Number.isNaN(Date.parse(s)), "must be a valid ISO date");
var list_strategy_bookings_default = defineTool3({
  name: "list_strategy_bookings",
  title: "List strategy bookings (admin)",
  description: "Admin-only. List TrendFlux strategy call bookings whose scheduled slot falls between `from` and `to` (inclusive). Supports pagination (`limit` + `offset`) and sorting (`sort_by` + `sort_dir`) so large date ranges can be exported page-by-page without timeouts. Returns contact info, session type, status, meeting link, timestamps, and pagination metadata.",
  inputSchema: {
    from: isoDate,
    to: isoDate,
    status: z.enum(["pending", "confirmed", "cancelled", "completed", "no_show"]).optional().describe("Optional status filter."),
    limit: z.number().int().min(1).max(500).optional().describe("Page size (default 200, max 500)."),
    offset: z.number().int().min(0).optional().describe("Row offset for pagination (default 0). Use `next_offset` from the previous page."),
    sort_by: z.enum(["scheduled_slot", "confirmed_slot_iso", "requested_slot_iso", "created_at", "updated_at"]).optional().describe("Sort column. `scheduled_slot` (default) sorts by confirmed_slot_iso and falls back to requested_slot_iso for pending rows."),
    sort_dir: z.enum(["asc", "desc"]).optional().describe("Sort direction (default `asc`).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, status, limit, offset, sort_by, sort_dir }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const { data: isAdmin, error: roleErr } = await supabase.rpc("current_user_has_role", {
      _role: "admin"
    });
    if (roleErr) {
      return { content: [{ type: "text", text: `Role check failed: ${roleErr.message}` }], isError: true };
    }
    if (!isAdmin) {
      return { content: [{ type: "text", text: "Forbidden: admin role required." }], isError: true };
    }
    const fromIso = new Date(from).toISOString();
    const toIso = new Date(to).toISOString();
    if (fromIso > toIso) {
      return { content: [{ type: "text", text: "`from` must be earlier than or equal to `to`." }], isError: true };
    }
    const pageSize = limit ?? 200;
    const pageOffset = offset ?? 0;
    const dir = sort_dir ?? "asc";
    const asc = dir === "asc";
    const sortCol = sort_by ?? "scheduled_slot";
    const rangeFilter = `and(confirmed_slot_iso.gte.${fromIso},confirmed_slot_iso.lte.${toIso}),and(confirmed_slot_iso.is.null,requested_slot_iso.gte.${fromIso},requested_slot_iso.lte.${toIso})`;
    const selectCols = "id, name, email, phone, company, goal, session_type, status, requested_slot_iso, confirmed_slot_iso, meet_url, client_timezone, organizer_timezone, created_at, updated_at";
    let query = supabase.from("strategy_bookings").select(selectCols, { count: "exact" }).or(rangeFilter);
    if (status) query = query.eq("status", status);
    if (sortCol === "scheduled_slot") {
      query = query.order("confirmed_slot_iso", { ascending: asc, nullsFirst: !asc }).order("requested_slot_iso", { ascending: asc });
    } else {
      query = query.order(sortCol, { ascending: asc });
    }
    query = query.order("id", { ascending: true });
    query = query.range(pageOffset, pageOffset + pageSize - 1);
    const { data, error, count } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const rows = data ?? [];
    const total = count ?? rows.length + pageOffset;
    const returned = rows.length;
    const hasMore = pageOffset + returned < total;
    const nextOffset = hasMore ? pageOffset + returned : null;
    const summary = `${returned} of ${total} booking(s) between ${fromIso} and ${toIso}${status ? ` (status=${status})` : ""} \u2014 page offset=${pageOffset}, size=${pageSize}, sort=${sortCol} ${dir}${hasMore ? `, next_offset=${nextOffset}` : `, end of results`}.`;
    return {
      content: [
        { type: "text", text: summary },
        { type: "text", text: JSON.stringify(rows, null, 2) }
      ],
      structuredContent: {
        bookings: rows,
        from: fromIso,
        to: toIso,
        count: returned,
        total,
        offset: pageOffset,
        limit: pageSize,
        next_offset: nextOffset,
        has_more: hasMore,
        sort_by: sortCol,
        sort_dir: dir
      }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dnodqhwwzdqfqlndwhsf";
var mcp_default = defineMcp({
  name: "trendflux-mcp",
  title: "TrendFlux Digital",
  version: "0.1.0",
  instructions: "Tools for the signed-in TrendFlux user. Use `get_my_profile` to read the user's profile, `list_my_enrollments` to list their TrendFlux Academy course enrollments, and (admins only) `list_strategy_bookings` to pull strategy calls in a date range for reporting and follow-ups.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_my_enrollments_default, list_strategy_bookings_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
